---
- name: install supervisor
  pip: name=supervisor state=present version=4.2.5

- name: link supervisor
  file:
    path: /usr/bin/{{ item }}
    state: link
    src: /usr/local/bin/{{ item }}
  with_items:
    - supervisord
    - supervisorctl

- name: check for sysvinit conf
  stat: path=/etc/init.d/supervisor
  register: init_d_conf

- name: service stop supervisor
  service: name=supervisor state=stopped
  when: init_d_conf.stat.exists

- name: pkill supervisord if run by cchq
  command: pkill -U cchq supervisord
  register: result
  # rc = 0: one or more processes match
  # rc = 1: no processes match
  failed_when: result.rc > 1
  changed_when: result.rc == 0

- name: remove /etc/init.d/supervisor
  file: state=absent path=/etc/init.d/supervisor
  when: init_d_conf.stat.exists

- name: remove default /etc/supervisor directory
  file: state=absent path=/etc/supervisor

- name: configure supervisor
  template: src=supervisord.conf.j2 dest=/etc/supervisord.conf

- name: Add Systemd Conf
  template:
    src: supervisord.systemd.service.j2
    dest: /etc/systemd/system/supervisord.service
  register: service_conf

- name: stop supervisor to pick up configuration changes
  service: name=supervisord state=stopped
  register: result
  failed_when: result.get("rc", -1) > 1
  changed_when: result.get("rc") == 0
  when: service_conf.changed

- name: pkill supervisord if run by cchq
  command: pkill -9 -U cchq supervisord
  # if it returns 1 with no output, that just means no process to kill
  register: result
  # rc = 0: one or more processes match
  # rc = 1: no processes match
  failed_when: result.rc > 1
  changed_when: result.rc == 0
  when: service_conf.changed

- name: start and enable supervisord
  service: name=supervisord enabled=yes state=started
  tags:
    - after-reboot
